tap "aquasecurity/trivy"
tap "aws/tap"
tap "buo/cask-upgrade"
tap "cloudfoundry/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "kryptco/tap"
tap "minio/stable"
brew "autoconf"
brew "automake"
brew "awscli"
brew "gettext"
brew "glib"
brew "certbot"
brew "circleci"
brew "libtool"
brew "pkg-config"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "ffmpeg"
brew "fswatch"
brew "gcc"
brew "gdb"
brew "gist"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "graphicsmagick"
brew "helm"
brew "hub"
brew "libheif"
brew "imagemagick"
brew "intltool"
brew "ipmitool"
brew "iproute2mac"
brew "jq"
brew "kubernetes-cli", link: false
brew "libiconv"
brew "libssh"
brew "mas"
brew "node"
brew "openjdk"
brew "packer"
brew "pango"
brew "poppler"
brew "pdf2svg"
brew "pigz"
brew "pinentry-mac"
brew "pstoedit"
brew "python@3.8"
brew "qemu"
brew "rancher-cli"
brew "ruby-build"
brew "rbenv"
brew "rclone"
brew "rpm"
brew "rsync"
brew "ruby"
brew "sl"
brew "telnet"
brew "terraform"
brew "tree"
brew "unar"
brew "wakeonlan"
brew "watch"
brew "wget"
brew "yarn"
brew "zsh"
brew "aquasecurity/trivy/trivy"
brew "aws/tap/aws-sam-cli"
brew "cloudfoundry/tap/bosh-cli"
brew "cloudfoundry/tap/bbl"
brew "minio/stable/mc"
cask "1password"
cask "amethyst"
cask "appcleaner"
cask "arduino"
cask "burp-suite"
cask "discord"
cask "docker"
cask "duet"
cask "firefox"
cask "ghidra"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hex-fiend"
cask "imageoptim"
cask "inkscape"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "macs-fan-control"
cask "microsoft-edge"
cask "ngrok"
cask "obs"
cask "phpstorm"
cask "pycharm"
cask "slack"
cask "soundflower"
cask "teamviewer"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "webstorm"
cask "wireshark"
cask "xquartz"
cask "zoomus"
mas "Apple Configurator 2", id: 1037126344
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
