tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "telnet"
brew "wget"
brew "mas"

cask "amethyst"
cask "karabiner-elements"
cask "xquartz"

cask "docker"
cask "visual-studio-code"
cask "intelij-idea"
cask "pycharm"

cask "slack"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "bitwarden" 
cask "microsoft-office"
cask "inkscape"
cask "insomnia"
cask "mailspring"
cask "shazam"
cask "imageoptim"
cask "duet"
cask "onedrive"
cask "google-backup-and-sync"
cask "adobe-creative-cloud"
cask "lego-mindstorms-ev3"

